#include <iostream>          //TRENGER KANSKJE FLERE**********
#include "CONST.H"
#include "FUNKSJONER.H"

// EIENDOM

void eiendomSwitch(){

}

void eiendomDisplay(){

}

void eiendomNy(){

}

void eiendomSlett(){

}

void eiendomEndere(){

}

// SONE

void soneDisplay(){

}

// KUNDER

void kundeSwitch(){

}

void kundeDisplay(){

}

void kundeNy(){

}

void kundeSlett(){

}

void kundeEndre(){

}

// ANNET

void ukeUtskrift(){

}

void lagNavn(char* t, char* s1, char* s2, int n, const int LEN){

}

void lesValg(){

}